### ISSUE TITLE
[BUG] exo run handles lots of output poorly

### ISSUE THREAD

**Issue by BenElgar** [deref/exo#127]
**Describe the bug**
If a command outputs a vast amount of logs exo run doesn't appear able to stop.

**To Reproduce**
1. Create a docker compose that looks like this:
```
services:
  busy:
    image: bash
    command: "bash -c 'while true; do echo hello; done'"
```
2. Send a SIGINT or SIGTERM to the `exo run` process
3. Witness as nothing happens

**Expected behavior**
The workspace should stop, terminating the container.

My assumption is that this happens because of the very large amount of output that the script generates.
