### ISSUE TITLE
[BUG] Exo logging slow with lots of services

### ISSUE THREAD

**Issue by BenElgar** [deref/exo#203]
**Describe the bug**
The following docker compose file takes a long time to start outputting logs in the terminal. 
```yaml
services:
  t1:
    image: bash
    command: sh -c 'i=0; while true; do echo $((i++)); sleep 1; done'
  t2:
    image: bash
    command: sh -c 'i=0; while true; do echo $((i++)); sleep 1; done'
  t3:
    image: bash
    command: sh -c 'i=0; while true; do echo $((i++)); sleep 1; done'
  t4:
    image: bash
    command: sh -c 'i=0; while true; do echo $((i++)); sleep 1; done'
  t5:
    image: bash
    command: sh -c 'i=0; while true; do echo $((i++)); sleep 1; done'
  t6:
    image: bash
    command: sh -c 'i=0; while true; do echo $((i++)); sleep 1; done'
  t7:
    image: bash
    command: sh -c 'i=0; while true; do echo $((i++)); sleep 1; done'
  t8:
    image: bash
    command: sh -c 'i=0; while true; do echo $((i++)); sleep 1; done'
  t9:
    image: bash
    command: sh -c 'i=0; while true; do echo $((i++)); sleep 1; done'
```

It takes about 30 seconds to start getting logs. From `docker ps` and from the output in the logs I can see that the containers themselves have been running for almost all of that time. The logs are then updated about once every 20 seconds.
