### ISSUE TITLE
[FEATURE] Support extended volumes syntax

### ISSUE THREAD

**Issue by BenElgar** [deref/exo#219]
A docker compose file like the following doesn't work because we don't support the extended volumes syntax:
```
services:
  web:
    image: bash
    volumes:
      - type: volume
        source: mydata
        target: /data
        volume:
          nocopy: true
      - type: bind
        source: ./static
        target: /opt/app/static
volumes:
  mydata:
```

You get an error of the following form:
```
applying manifest: job failure: unmarshalling spec: cannot unmarshal map[string]interface {} into Go struct field Spec.Volumes of type string
```
