### ISSUE TITLE
[BUG] Cannot connect docker container to multiple networks

### ISSUE THREAD

**Issue by BenElgar** [deref/exo#259]
Docker compose file:
```
services:
  t0:
    image: nginx
    command: sleep infinity
    networks:
      - n1
      - n2
networks:
  n2: {}
  n1: {}
```

This seems to cause issues of the following form:
```
adding replacement "t0": creating container: Error response from daemon: Container cannot be connected to network endpoints: tmpkvhNU3IChI_n1, tmpkvhNU3IChI_n2
```
